### ISSUE TITLE
error. can you help me plz

### ISSUE THREAD

**Issue by tuyeen1509** [hpc203/yolov5-dnn-cpp-python#23]
Traceback (most recent call last):
  File "C:/Users/xtuye/yolov5-dnn-cpp-python/main_yolov5.py", line 114, in <module>
    dets = yolonet.detect(srcimg)
  File "C:/Users/xtuye/yolov5-dnn-cpp-python/main_yolov5.py", line 90, in detect
    outs[i] = outs[i].reshape(bs, self.na, self.no, ny, nx).transpose(0, 1, 3, 4, 2)
TypeError: 'tuple' object does not support item assignment

**Comment by zengxianl** [comment]
do solve this?
